//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoesShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int OrderID { get; set; }
        public int ProductID { get; set; }
        public System.DateTime DateOrder { get; set; }
        public System.DateTime DateDelivery { get; set; }
        public int PointID { get; set; }
        public int UserID { get; set; }
        public string Code { get; set; }
        public int StatusID { get; set; }
        public int Quantity { get; set; }
    
        public virtual Points Points { get; set; }
        public virtual Products Products { get; set; }
        public virtual Statuses Statuses { get; set; }
        public virtual Users Users { get; set; }
    }
}
